using UnityEngine;
using UnityEngine.SceneManagement;

/**
* The following codes are generated by ChatGPT
* Prompt: 如何设置点击某一辆小车就跳转到某个scene，并且同时还把小车的id给传过去？
**/
public class CarClickHandler : MonoBehaviour
{
    public string carID; // 设置为每辆车的唯一ID
    public string targetScene = "CarDetailScene"; // 你想跳转的目标场景

    private void OnMouseDown()
    {
        // 方式一：使用 PlayerPrefs 传递 ID
        PlayerPrefs.SetString("SelectedCarID", carID);
        PlayerPrefs.Save();

        // 加载新场景
        SceneManager.LoadScene(targetScene);
    }

    void Update()
    {
        if (Input.GetMouseButtonDown(0))
        {
            Ray ray = Camera.main.ScreenPointToRay(Input.mousePosition);
            if (Physics.Raycast(ray, out RaycastHit hit))
            {
                Debug.Log("点击到了：" + hit.collider.name);
            }
        }
    }
}
